Request Model #9
hatchways/team-spearmint pull request #57
Opened 2022-02-01 21:46 UTC by seblaifa3315

### What this PR does (required):
- l created a Request model

### Any information needed to test this feature (required):
- I was not sure of the default values for the property "start" (date requested to start) and "end" (date requested to end). So, for "start" I gave a default value of current date, and  for "end" I gave a default value of current date + 1 day.

### Any issues with the current functionality (optional):
- For the properties default values of "start" and "end" I'm not sure about the implementation:

start: {
...
            default: **Date.now,**  --OR--  **Date.now(),**
        },
        end: {
...
            default: **() => Date.now() + 24x60x60x1000,**  --OR-- **Date.now() + 24x60x60x1000**
        },

2022-02-04 20:23 UTC, ezeilo-su commented
Hey @seblaifa3315, kindly link your ticket. Kindly follow this [guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) if you need help.

2022-02-05 17:31 UTC, ezeilo-su requested changes
Good progress so far.
Happy coding!

2022-02-05 17:31 UTC, ezeilo-su commented on server/models/Request.js
> +    }
Hey @seblaifa3315, use `camelCase` for your variable names. Use the proper linters setup in your editor to format your code.

2022-02-08 18:33 UTC, seblaifa3315 commented
- I changed to camelCase
- I added some properties

2022-02-08 18:37 UTC, rajivtitus commented on server/models/Request.js
> +        timestamps: true
👍🏽

2022-02-08 18:37 UTC, rajivtitus commented on server/models/Request.js
> +        ownerId: {
👍🏽

2022-02-08 18:39 UTC, rajivtitus commented on server/models/Request.js
> +        ownerName: {
Let's remove a few fields from this model as we wouldn't want to duplicate data across our db. Please see below for fields to be removed:
- ownerName
- ownerPhoto
- sitterName
- location

2022-02-08 18:42 UTC, rajivtitus commented on server/models/Request.js
> +        accepted: {
Additionally, we can consolidate the `accepted/declined` fields under a single enum type object.

Example: 
```
status: {
    type: String,
    enum: ['pending', 'accepted', 'declined', 'completed']
    default: 'pending'
    lowercase: true,
    required: true,
  }
```

2022-02-08 18:44 UTC, rajivtitus commented on server/models/Request.js
> +        end: {
Optional: We can also add a schema validation to check if the end > start

2022-02-08 18:45 UTC, rajivtitus reviewed
Good work with this Sebastien! Just a couple of comments to address here 👍🏽

2022-02-09 01:54 UTC, seblaifa3315 commented
- I removed few field as addressed in the comments above
- I combined the accepted and declined status into one field "status"
- I  added a schema validation to check if the end > start

2022-02-11 00:11 UTC, rajivtitus approved these changes
LGTM, good work with the changes 👍🏽

2022-02-11 02:12 UTC, merged