Feature manage bookings UI #19
hatchways/team-spearmint pull request #60
Opened 2022-02-04 21:51 UTC by seblaifa3315

### What this PR does (required):
- Created the Manage Bookings Page UI.
- This view is for pet sitters who have requests coming in and have the ability to manage their bookings.

### Screenshots / Videos (front-end only):
![manageBookings](https://user-images.githubusercontent.com/77294017/152606896-1e6a3ed0-10d4-4b16-a183-a7eecce701eb.jpg)

### Any information needed to test this feature (required):
- To access the page go path ="/manageBookings"
- Attention: In this ticket I focused only on the UI, so everything is hard coded. I will fetch the data from the database in my next ticket (Integration).

### Any issues with the current functionality (optional):
1. I chose the Settings Icon from material UI but it is not exactly the same that the mockup
2. In the the Calendar component:
- I haven't been able to change the color of the arrows
- I haven't been able to remove the double arrows
- I haven't been able to have a circle background on the active date
- I haven't been able to to find how to allowed multi selection

2022-02-05 17:09 UTC, ezeilo-su requested changes
Hey @seblaifa3315, please address all the comments I left below. Good work overall :+1:

2022-02-05 17:09 UTC, ezeilo-su commented on client/src/components/MyCalendar/myCalendar.css
> +  } */
Let's get rid of this comment block

2022-02-05 17:09 UTC, ezeilo-su commented on client/src/components/MyCalendar/myCalendar.css
> +  } */
Let's remove this one too

2022-02-05 17:09 UTC, ezeilo-su commented on client/src/components/MyCalendar/myCalendar.css
> +  } */
Please let's clean up our code by removing all the commented-out code

2022-02-05 17:09 UTC, ezeilo-su commented on client/src/components/MyCalendar/myCalendar.css
> +  } */
Remove this

2022-02-05 17:09 UTC, ezeilo-su commented on client/src/components/MyCalendar/myCalendar.css
> +  } */
This one too

2022-02-08 19:34 UTC, seblaifa3315 commented
I removed all the comment from style of MyCalendar component as addressed in the comments above.
I still have to work on the calendar style to match the mockup

2022-02-08 19:50 UTC, rajivtitus commented on client/src/App.tsx
> +                <Route exact path="/manageBookings" component={ManageBookings} />
```suggestion
                <Route exact path="/manage-bookings" component={ManageBookings} />
```
We use hyphenated case for routes names in JS

2022-02-08 19:51 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +  size?: any;
Let's avoid using `any` as a type

2022-02-08 19:55 UTC, rajivtitus commented on client/src/components/CardWrapper/CardWrapper.tsx
> +const CardWrapper: React.FC<CardWrapperProps> = ({ children }) => {
We can use the MUI Card API and assign a class to it with the below styles, I don't think we need to make a separate `CardWrapper` here :)

2022-02-08 19:57 UTC, rajivtitus commented on client/src/components/CardWrapper/CardWrapper.tsx
> +const CardWrapper: React.FC<CardWrapperProps> = ({ children }) => {
I don't think we need to componentize this, since it's just a Box/Paper component with a few styles :)

2022-02-08 19:58 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +    <Box className={clsx(classes.requestInfo, size === 'large' && classes.requestInfoLarge)}>
We can use the MUI Card API to add semantic meaning - as each booking card contains info about a particular booking

Ref: https://mui.com/api/card/

2022-02-08 19:59 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +            sx={size === 'large' ? { width: 50, height: 50 } : { width: 40, height: 40 }}
Also, wouldn't it be better to use breakpoints to apply styles for large/small screens accordingly?

2022-02-08 20:01 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +const RequestInfo: React.FC<{
Let's abstract this component into its own file

2022-02-08 20:01 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +                  key="123"
Rather than passing multiple props, it would be easier to pass the entire booking object to a request card

2022-02-08 20:02 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +                    key="123"
As opposed to hardcoding these props, we can have an array of object with mock data and map over it

2022-02-08 20:02 UTC, rajivtitus commented on client/src/pages/ManageBookings/useStyles.ts
> +    display: 'flex',
Some of the styles within this file can be applied directly to the relevant MUI component

2022-02-08 20:03 UTC, rajivtitus reviewed
UI looks good 💯 
Some comments to clean up the code and increase maintainability, please let me know if you have any questions

2022-02-09 18:47 UTC, seblaifa3315 commented
I made the changes according to the comments above except 2 things:
1. "We can use the MUI Card API to add semantic meaning - as each booking card contains info about a particular booking":  I got lost trying to change to MUI Card. Need to come back on it later
2. "Also, wouldn't it be better to use breakpoints to apply styles for large/small screens accordingly?": this props was not meant to change the style depending on the size of the screen, but it is to create 2 different styles depending on if it is the "Next booking" info (bigger font, no border, more spacing...)  or the "current Bookings" and "Past Bookings" Info which has a smaller font, border etc... See the mockup.

2022-02-11 16:51 UTC, rajivtitus commented
> I made the changes according to the comments above except 2 things:
> 
> 1. "We can use the MUI Card API to add semantic meaning - as each booking card contains info about a particular booking":  I got lost trying to change to MUI Card. Need to come back on it later
> 2. "Also, wouldn't it be better to use breakpoints to apply styles for large/small screens accordingly?": this props was not meant to change the style depending on the size of the screen, but it is to create 2 different styles depending on if it is the "Next booking" info (bigger font, no border, more spacing...)  or the "current Bookings" and "Past Bookings" Info which has a smaller font, border etc... See the mockup.

1. If you follow the MUI docs, it is a pretty simple implementation. Did you have any specific questions?
2. Thanks for the clarification 👍🏽

2022-02-11 16:55 UTC, rajivtitus commented on client/src/pages/ManageBookings/useStyles.ts
> +    display: 'flex',
@seblaifa3315 Please address the above comment

2022-02-11 16:55 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +const dummyData = [
👍🏽

2022-02-11 16:56 UTC, rajivtitus commented on client/src/pages/ManageBookings/ManageBookings.tsx
> +    <Box className={clsx(classes.requestInfo, size === 'large' && classes.requestInfoLarge)}>
@seblaifa3315 This comment is yet to be addressed too :)

2022-02-11 16:57 UTC, rajivtitus commented
@seblaifa3315 Thanks for making the changes! Just a couple of pending comments to be addressed, please let me know if you have any questions

2022-02-12 07:00 UTC, seblaifa3315 commented
1. I changed to MUI Card for the requestInfo component
2. I still have an issue with the calendar: I can't figure out how to make the active day circle. It changes from ellipse to circle when we change the size of the screen. Any hint?

2022-02-16 18:02 UTC, rajivtitus commented on client/src/components/RequestInfo/MyModal.tsx
> +        <Typography id="modal-modal-title" variant="h6" component="h2"></Typography>
This `Typography` component has no text within it, let's remove it or add the appropriate title here

2022-02-16 18:04 UTC, rajivtitus commented on client/src/components/RequestInfo/MyModal.tsx
> +                <Typography style={{ color: '#c7c7c7', fontSize: '10px' }}>Accept</Typography>
Please avoid the usage of inline styles

Ditto where applicable

2022-02-16 18:07 UTC, rajivtitus commented on client/src/pages/ManageBookings/useStyles.ts
> +    display: 'flex',
@seblaifa3315 Please address comment before merging

2022-02-16 18:08 UTC, rajivtitus commented on client/src/components/RequestInfo/MyModal.tsx
> +              <Box
We can also swap out this `Box` component for a MUI `Button`

Ditto throughout this file

2022-02-16 18:13 UTC, rajivtitus commented
> 1. I changed to MUI Card for the requestInfo component
> 2. I still have an issue with the calendar: I can't figure out how to make the active day circle. It changes from ellipse to circle when we change the size of the screen. Any hint?

1. Good work
2. Try changing the padding and the height for the tile using the `.react-calendar__tile` class

2022-02-16 18:13 UTC, rajivtitus approved these changes
LGTM! Thanks for the changes, please address pending comment before merging

2022-03-01 09:16 UTC, rajivtitus commented
If the UI changes are already a part of the `develop` branch then let's close this PR?

2022-03-17 20:05 UTC, merged