Setup stripe api #40
hatchways/team-spearmint pull request #71
Opened 2022-02-22 21:42 UTC by natey37

### What this PR does (required):
- Hook up Stripe functionality 
- Set up frontend UI to save credit cards as payment options
- Set up API calls to retrieve users payment options, default option, and to create a new payment option
- Set up routing for Stripe controller, create back end routes:
- POST to create a new customer as well as save their payment option
- GET to all of the customers payment options
- PATCH to set a card as the default payment option

### Screenshots / Videos (front-end only):
![Screen Shot 2022-02-22 at 1 17 50 PM](https://user-images.githubusercontent.com/20386173/155222278-f25cebd3-b930-44f3-9a12-8898e8b5e0bb.png)
![Screen Shot 2022-02-22 at 1 18 03 PM](https://user-images.githubusercontent.com/20386173/155222296-a3d5baf8-54e1-4ec2-ac33-179e4e2a59d2.png)
![Screen Shot 2022-02-22 at 1 18 11 PM](https://user-images.githubusercontent.com/20386173/155222314-ac07b8fd-84d8-4c11-a9d8-1181c12ad1fb.png)

### Any information needed to test this feature (required):
- Need stripe API keys to test feature, message me in slack for keys!

### Any issues with the current functionality (optional):
- Should probably add a route to delete a payment?
- Also I think this PR is 3 different tickets...let me know if I should create multiple PRs and cherry pick commits?

2022-02-23 17:56 UTC, ezeilo-su requested changes
Hey @natey37, good work with this one. Kindly have a look at my comments and address them.
Happy coding!

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/components/Stripe/CheckoutForm.tsx
> +      console.log(newPayment.clientSecret);
Let's remove these console logs, please.

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/components/Stripe/CheckoutForm.tsx
> +        console.log(setupIntent);
Remove console log

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/components/Stripe/CheckoutForm.tsx
> +//   );
Please let's remove comments/unused code to keep our code clean

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/helpers/APICalls/createPayment.ts
> +    // body: JSON.stringify({ id: profileId }),
Let's remove

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/pages/Settings/Payment/Payment.tsx
> +  console.log(defaultPaymentMethod);
Remove console logs

2022-02-23 17:56 UTC, ezeilo-su commented on client/src/pages/Settings/Payment/Payment.tsx
> +                    <img className={classes.cardLogo} src={logo()}></img>
This `img` tag is missing an `alt` attribute. Please kindly add one :smiley:

2022-02-23 17:56 UTC, ezeilo-su commented on server/controllers/stripe.js
> +// @access private
Good documentation

2022-02-23 17:56 UTC, ezeilo-su commented on server/controllers/stripe.js
> +  console.log(req.user.id)
Lt's get rid of this one

2022-02-23 17:56 UTC, ezeilo-su commented on server/controllers/stripe.js
> +//@access private
:+1:

2022-02-24 12:09 UTC, ezeilo-su reviewed
Good work making the requested changes :+1:

2022-03-01 11:03 UTC, rajivtitus commented on server/controllers/stripe.js
> +    let savedProfile = await profile.save()
```suggestion
    const savedProfile = await profile.save()
```
I don't see us reassigning this variable

2022-03-01 11:06 UTC, rajivtitus approved these changes
Good work with this feature! 👍🏽

2022-03-02 06:43 UTC, merged