Feature profile details integration #35
hatchways/team-spearmint pull request #72
Opened 2022-02-25 17:46 UTC by seblaifa3315

### What this PR does (required):
- Made profile details page dynamic based on user using params which should be pushed from listing profile page
-  Added functionality to create a request to the specific sitter based on the date picker

### Any information needed to test this feature (required):
- login with email "johndoe@gmail.com" and password "johndoe"
- go to the path="/profile-details/:sitterId"

**Here are some sitterId to use as params:**
62042faa5acc1804d4ad8874
620545804d573a441a7ac55f
6204307506cc5874cc5022ad
620544e34d573a441a7ac547
6205450b4d573a441a7ac54d
6205452d4d573a441a7ac553
620545594d573a441a7ac559

2022-02-25 20:12 UTC, ezeilo-su requested changes
Hey @0916dhkim, please remove all the duplicate files in your project.

2022-02-25 20:12 UTC, ezeilo-su commented on server/controllers/request 2.js
> +exports.createRequest = async (req, res) => {
Let's wrap this handler with the `asyncHandler` middleware.

2022-02-25 20:12 UTC, ezeilo-su commented on server/controllers/request 2.js
> +exports.getRequests = async (req, res) => {
The same here as with the comment above

2022-02-25 20:12 UTC, ezeilo-su commented on server/controllers/request 2.js
> +exports.updateRequest = async (req, res) => {
This one too

2022-02-25 20:12 UTC, ezeilo-su commented on server/controllers/request.js
> +};
It seems your duplicated these ones

2022-02-25 20:12 UTC, ezeilo-su commented on server/models/Request 3.js
> +module.exports = Request = mongoose.model("Request", requestSchema);
Please remove duplicate schema

2022-02-25 20:12 UTC, ezeilo-su commented on server/routes/request 2.js
> +module.exports = router;
Duplicate file, please remove.

2022-03-01 10:24 UTC, rajivtitus commented on client/src/App.tsx
> +                <Route path="/profile-details/:sitterId" component={ProfileDetails} />
👍🏽

2022-03-01 10:27 UTC, rajivtitus commented on server/controllers/request.js
> +    console.log(req.body);
Please remove logs to the console

2022-03-01 10:28 UTC, rajivtitus reviewed
Good work with this! I noticed that we have duplicates for the request model, routes and controllers - please delete the outdated versions and update this PR 👍🏽

2022-03-04 20:50 UTC, rajivtitus commented on client/src/components/Navbar/Navbar.tsx
> +  interface IAccountType {
```suggestion
  interface AccountType {
```
Please avoid using 'I' as a prefix for interfaces in JS

2022-03-04 20:50 UTC, rajivtitus commented on server/models/Profile.js
> +    default: 'other',
We don't want to have a default gender 😄

2022-03-04 20:51 UTC, rajivtitus approved these changes
LGTM! Thanks for making those changes 👍🏽

2022-03-06 08:43 UTC, merged